name: Testing with Pytest
run-name: Pytest
on:
  push:
    branches:
      - main
      - 'releases/**'
    # removed "branches-ignore: dev" as itcan't be used together with "branches"

  # replaced "label" and "issues" triggers with pull_request
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # changed from v2 to v4

    - name: Set up Python
      uses: actions/setup-python@v5  # changed from v2 to v5
      with:
        python-version: "3.11"  # upgraded to 3.11. 3.8 is end-of-life
        cache: pip  # caches pip packages for faster installs

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests and generate XML report
      run: pytest --junitxml=pytest-report.xml
      # removed "continue-on-error: false" as it's the default

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4  # changed from v2 to v4 as v2 no longer works
      with:
        name: test-results
        path: pytest-report.xml

    - name: Notify on success
      if: success()
      run: echo "Tests passed successfully"

    - name: Notify on failure
      if: failure()
      run: echo "Tests failed"