name: Testing Github Lab1 with Pytest
run-name: Pytest
on:
  push:
    branches:
      - main
      - 'releases/**'

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Labs/Github_Labs/Lab1  # run commands from the Lab1 folder
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: pip
        cache-dependency-path: Labs/Github_Labs/Lab1/requirements.txt

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests and generate XML report
      run: pytest --junitxml=pytest-report.xml

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: Labs/Github_Labs/Lab1/pytest-report.xml  # working-directory doesn't apply to "with:" paths

    - name: Notify on success
      if: success()
      run: echo "Tests passed successfully"

    - name: Notify on failure
      if: failure()
      run: echo "Tests failed"
